import assert from "node:assert/strict";
import test from "node:test";
import {classifyScore,DEFAULT_SCORING_RULES,LeadScoringEngine,prioritizeScore} from "../lib/intelligence/lead-scoring-engine";
import {LeadIntelligenceService} from "../lib/intelligence/lead-intelligence-service";
import {queryRadar} from "../lib/intelligence/radar";
import {InMemoryIntelligenceActivityRepository,InMemoryLeadAnalysisRepository,type LeadIntelligenceDataSource} from "../lib/intelligence/repositories";
import type {LeadIntelligenceInput} from "../lib/intelligence/types";

const base:LeadIntelligenceInput={id:"lead-a",campaignId:"campaign-a",name:"Empresa A",category:"Serviços",city:"Campinas",website:"https://example.com",phone:"11999999999",hasWhatsapp:false,hasInstagram:false,address:"Rua A",rating:4,reviews:10,hasAutomationSignals:false};
const engine=new LeadScoringEngine();
class MutableSource implements LeadIntelligenceDataSource{constructor(public leads:LeadIntelligenceInput[]){}async campaignExists(id:string){return this.leads.some(item=>item.campaignId===id)}async findLeadById(id:string){return this.leads.find(item=>item.id===id)}async findLeadsByCampaignId(id:string,options:{offset?:number;limit?:number}={}){const leads=this.leads.filter(item=>item.campaignId===id),offset=options.offset??0;return leads.slice(offset,options.limit?offset+options.limit:undefined)}async countLeadsByCampaignId(id:string){return this.leads.filter(item=>item.campaignId===id).length}async listLeads(){return this.leads}}
function setup(leads=[base]){const source=new MutableSource(leads);const repo=new InMemoryLeadAnalysisRepository();const activities=new InMemoryIntelligenceActivityRepository();return {source,repo,activities,service:new LeadIntelligenceService(source,engine,repo,activities)}}

test("empresa sem site recebe 30 pontos pela regra",()=>{const analysis=engine.analyze({...base,website:null});assert.ok(analysis.reasons.includes("Sem website: +30"))});
test("telefone e WhatsApp acrescentam os pontos configurados",()=>{const without=engine.analyze({...base,phone:null,hasWhatsapp:false});const withContact=engine.analyze({...base,phone:"119",hasWhatsapp:true});assert.equal(withContact.score-without.score,30)});
test("score é limitado entre zero e cem",()=>{const high=new LeadScoringEngine({...DEFAULT_SCORING_RULES,noWebsite:100}).analyze({...base,website:null,hasWhatsapp:true,hasInstagram:true,rating:5,reviews:1000});const low=engine.analyze({...base,name:"",category:"",city:"",website:undefined,phone:null,address:null});assert.equal(high.score,100);assert.equal(low.score,0)});
test("classificações respeitam todas as fronteiras",()=>{assert.deepEqual([39,40,59,60,79,80].map(classifyScore),["Baixo","Regular","Regular","Bom","Bom","Excelente"])});
test("prioridades respeitam as faixas de score",()=>{assert.deepEqual([20,59,60,79,80,100].map(prioritizeScore),["Baixa","Baixa","Média","Média","Alta","Alta"])});
test("recomendações mudam conforme sinais do lead",()=>{const noSite=engine.analyze({...base,website:null});const mature=engine.analyze({...base,website:"https://site.example",reviews:120,hasAutomationSignals:true});assert.ok(noSite.recommendedServices.some(item=>item.name==="Site institucional"));assert.ok(!mature.recommendedServices.some(item=>item.name==="Site institucional"))});
test("dados ausentes são declarados sem inventar informação",()=>{const analysis=engine.analyze({...base,website:undefined,phone:null,address:null,rating:undefined,reviews:undefined,hasWhatsapp:undefined});for(const field of ["Website","Telefone","Endereço","Nota","Avaliações","WhatsApp"])assert.ok(analysis.missingData.includes(field))});
test("recálculo atualiza a análise existente sem duplicar",async()=>{const {service,source,repo}=setup();const first=await service.analyzeLead(base.id);source.leads[0]={...base,website:null};await new Promise(resolve=>setTimeout(resolve,2));const second=await service.analyzeLead(base.id,{recalculate:true});assert.equal((await repo.list()).length,1);assert.equal(second.id,first.id);assert.notEqual(second.updatedAt,first.updatedAt);assert.notEqual(second.score,first.score)});
test("análise em massa mantém campanhas isoladas",async()=>{const other={...base,id:"lead-b",campaignId:"campaign-b"};const {service,repo}=setup([base,other]);await service.analyzeCampaign("campaign-a");assert.deepEqual((await repo.list()).map(item=>item.leadId),["lead-a"])});
test("Radar ordena por score e usa avaliações como desempate",()=>{const a=engine.analyze(base);const better=engine.analyze({...base,id:"lead-b",website:null,reviews:120});const tie={...a,id:"analysis-c",leadId:"lead-c"};const result=queryRadar([{lead:base,analysis:a},{lead:{...base,id:"lead-b",website:null,reviews:120},analysis:better},{lead:{...base,id:"lead-c",reviews:99},analysis:tie}]);assert.equal(result[0].lead.id,"lead-b");assert.equal(result[1].lead.id,"lead-c")});
test("lead não analisado não aparece no Radar",async()=>{const {service,repo}=setup([base,{...base,id:"lead-b"}]);await service.analyzeLead("lead-a");const analyzed=await repo.list();const result=queryRadar([{lead:base,analysis:analyzed[0]}]);assert.deepEqual(result.map(item=>item.lead.id),["lead-a"])});
test("cálculo e recálculo registram atividades auditáveis",async()=>{const {service,activities}=setup();await service.analyzeLead(base.id);await service.analyzeLead(base.id,{recalculate:true});assert.deepEqual(activities.activities.map(item=>item.type),["lead_score_calculated","lead_analysis_recalculated"])});
