import assert from "node:assert/strict";
import test from "node:test";
import { MockLeadProvider, OutscraperLeadProvider } from "../lib/providers";
import { InMemoryLeadRepository, SearchCompaniesService } from "../lib/search-companies-service";

test("MockLeadProvider respects requested quantity and stable IDs",async()=>{const provider=new MockLeadProvider(),input={city:"Campinas",state:"SP",category:"Dentista",limit:7};const first=await provider.search(input),second=await provider.search(input);assert.equal(first.length,7);assert.deepEqual(first.map(item=>item.externalId),second.map(item=>item.externalId))});
test("provider pago exige confirmação antes de chamar a rede",async()=>{let calls=0;const fakeFetch:typeof fetch=async()=>{calls++;return new Response(JSON.stringify({data:[[{place_id:"place-1",name:"Clínica Teste",full_address:"Campinas, SP"}]]}),{status:200})};const provider=new OutscraperLeadProvider("test-key",fakeFetch);await assert.rejects(provider.search({city:"Campinas",category:"Dentista",limit:1}),/confirme/i);assert.equal(calls,0);const results=await provider.search({city:"Campinas",category:"Dentista",limit:1},{confirmedPaidUsage:true});assert.equal(results[0].externalId,"place-1");assert.equal(calls,1)});
test("SearchCompaniesService imports once and reports duplicates",async()=>{const repository=new InMemoryLeadRepository();const service=new SearchCompaniesService(new MockLeadProvider(),repository);const input={city:"Campinas",state:"SP",category:"Dentista",limit:3};const first=await service.execute("user-1","campaign-1",input);const second=await service.execute("user-1","campaign-1",input);assert.equal(first.stats.imported,3);assert.equal(second.stats.duplicates,3)});
test("Outscraper sem chave permanece desabilitado",async()=>{const provider=new OutscraperLeadProvider("");assert.equal(provider.configured,false);await assert.rejects(provider.search({city:"Campinas",category:"Dentista",limit:1}),/não configurada/i)});
