import assert from "node:assert/strict";
/* eslint-disable @typescript-eslint/no-explicit-any */
import test from "node:test";
import fs from "node:fs";
import {NoteService,TaskService,type SalesProductRepository} from "../lib/sales-product/service";
import type {LeadNote,SalesTask,TaskInput} from "../lib/sales-product/types";
import {dashboardMetrics,globalSearch} from "../lib/workspace-insights";
class MemoryRepo implements SalesProductRepository{tasks:SalesTask[]=[];notes:LeadNote[]=[];favorites=new Map<string,boolean>();activities:string[]=[];leads=new Map([["u1:l1",{campaignId:"c1"}],["u2:l2",{campaignId:"c2"}]]);async listTasks(user:string){return this.tasks.filter(x=>x.userId===user)}async getTask(user:string,id:string){return this.tasks.find(x=>x.userId===user&&x.id===id)}async leadContext(user:string,lead:string){return this.leads.get(`${user}:${lead}`)}async createTask(user:string,input:TaskInput){const now=new Date().toISOString(),item:SalesTask={id:`t${this.tasks.length+1}`,userId:user,leadId:input.leadId,campaignId:input.campaignId??null,title:input.title,description:input.description??null,type:input.type,priority:input.priority,scheduledFor:input.scheduledFor,status:"pendente",completedAt:null,createdAt:now,updatedAt:now};this.tasks.push(item);return item}async updateTask(user:string,id:string,patch:any){const item=await this.getTask(user,id);if(!item)throw new Error("não encontrada");Object.assign(item,patch);return item}async deleteTask(user:string,id:string){this.tasks=this.tasks.filter(x=>!(x.userId===user&&x.id===id))}async listNotes(user:string,lead:string){return this.notes.filter(x=>x.userId===user&&(!lead||x.leadId===lead))}async getNote(user:string,id:string){return this.notes.find(x=>x.userId===user&&x.id===id)}async createNote(user:string,leadId:string,text:string){const now=new Date().toISOString(),item={id:`n${this.notes.length+1}`,userId:user,leadId,text,createdAt:now,updatedAt:now};this.notes.push(item);return item}async updateNote(user:string,id:string,text:string){const item=await this.getNote(user,id);if(!item)throw new Error("não encontrada");item.text=text;item.updatedAt=new Date().toISOString();return item}async deleteNote(user:string,id:string){this.notes=this.notes.filter(x=>!(x.userId===user&&x.id===id))}async setFavorite(user:string,lead:string,value:boolean){if(!this.leads.has(`${user}:${lead}`))throw new Error("não encontrado");this.favorites.set(`${user}:${lead}`,value)}async activity(_:string,input:{type:string}){this.activities.push(input.type)}}
const taskInput={leadId:"l1",title:"Ligar",type:"ligacao" as const,priority:"alta" as const,scheduledFor:"2027-07-05T15:00:00.000Z"};
test("CRUD de tarefas persiste e audita",async()=>{const repo=new MemoryRepo(),service=new TaskService(repo),created=await service.create("u1",taskInput);assert.equal(created.campaignId,"c1");await service.update("u1",created.id,{title:"Enviar proposta"});await service.update("u1",created.id,{status:"concluida"});assert.ok((await repo.getTask("u1",created.id))?.completedAt);await service.delete("u1",created.id);assert.equal(repo.tasks.length,0);assert.deepEqual(repo.activities,["task_created","task_updated","task_completed","task_deleted"])});
test("CRUD de notas sanitiza e audita",async()=>{const repo=new MemoryRepo(),service=new NoteService(repo),note=await service.create("u1","l1","<b>Nota</b>");assert.equal(note.text,"bNota/b");await service.update("u1",note.id,"Editada");await service.delete("u1",note.id);assert.deepEqual(repo.activities,["note_created","note_updated","note_deleted"])});
test("favoritar e desfavoritar é persistente",async()=>{const repo=new MemoryRepo(),service=new NoteService(repo);await service.favorite("u1","l1",true);assert.equal(repo.favorites.get("u1:l1"),true);await service.favorite("u1","l1",false);assert.deepEqual(repo.activities,["lead_favorited","lead_unfavorited"])});
test("usuário não acessa tarefa de outro usuário",async()=>{const repo=new MemoryRepo();await new TaskService(repo).create("u1",taskInput);await assert.rejects(()=>new TaskService(repo).update("u2","t1",{title:"Inválida"}),/não encontrada/)});
test("lead de outra campanha é rejeitado",async()=>{await assert.rejects(()=>new TaskService(new MemoryRepo()).create("u1",{...taskInput,campaignId:"c2"}),/não pertence/)});
test("pesquisa inclui notas, histórico e tarefas",()=>{const data:any={leads:[{id:"l1",name:"Empresa",phone:"",city:"",state:"",category:"",notes:"decisor"}],campaigns:[],activities:[{leadId:"l1",note:"proposta especial",type:"task_created"}],messages:[],tasks:[{id:"t1",title:"Reunião diretoria",status:"hoje",priority:"alta"}]};assert.equal(globalSearch(data,"decisor").leads.length,1);assert.equal(globalSearch(data,"proposta especial").leads.length,1);assert.equal(globalSearch(data,"reunião").tasks.length,1)});
test("dashboard calcula favoritos e tarefas",()=>{const data:any={leads:[{status:"Novo",favorite:true}],campaigns:[],activities:[],messages:[{status:"scheduled"}],tasks:[{status:"hoje"},{status:"atrasada"},{status:"concluida"}]};const metrics=dashboardMetrics(data);assert.equal(metrics.favorites,1);assert.equal(metrics.tasksToday,1);assert.equal(metrics.tasksOverdue,1);assert.equal(metrics.tasksCompleted,1);assert.equal(metrics.scheduled,1)});
test("Agenda contém grupos, filtros e ordenação",()=>{const source=fs.readFileSync("app/AgendaPanel.tsx","utf8");for(const text of ["Hoje","Próximos dias","Atrasadas","Concluídas","priority","campaign","lead","status"])assert.match(source,new RegExp(text))});
test("pipeline mostra próxima tarefa, atividades e favorito",()=>{const source=fs.readFileSync("app/Workspace.tsx","utf8");assert.match(source,/Próxima tarefa/);assert.match(source,/atividades/);assert.match(source,/lead\.favorite/)});
test("migration habilita RLS sem políticas públicas",()=>{const sql=fs.readFileSync("supabase/migrations/202607160007_sprint9_tasks_notes.sql","utf8");assert.match(sql,/alter table public\.tasks enable row level security/);assert.match(sql,/alter table public\.lead_notes enable row level security/);assert.doesNotMatch(sql,/using\s*\(\s*true\s*\)/i);assert.match(sql,/user_id=auth\.uid\(\)/)});
test("cliente não importa Supabase nem server-only",()=>{for(const file of ["app/AgendaPanel.tsx","app/LeadSalesPanel.tsx"]){const source=fs.readFileSync(file,"utf8");assert.equal(source.split(/\r?\n/)[0],'"use client";');assert.doesNotMatch(source,/supabase|server-only|next\/headers/)}});
test("detalhe do lead usa banco e não mock",()=>{const source=fs.readFileSync("lib/workspace-data.ts","utf8"),section=source.slice(source.indexOf("export async function getLeadDetail"),source.indexOf("export async function getCampaignDetail"));assert.doesNotMatch(section,/MOCK_|mock-campaigns/);assert.match(section,/from\("leads"\)/)});
