"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";

type Lead = { id:number; name:string; category:string; city:string; score:number; status:string; site:boolean; phone:string; initials:string; tone:string };
const leads: Lead[] = [
  {id:1,name:"Sorriso Prime Odontologia",category:"Clínica odontológica",city:"Campinas, SP",score:92,status:"Interessado",site:false,phone:"(19) 99542-8170",initials:"SP",tone:"mint"},
  {id:2,name:"Studio Helena Arquitetura",category:"Arquitetura",city:"Campinas, SP",score:87,status:"Respondeu",site:true,phone:"(19) 99182-0406",initials:"SH",tone:"violet"},
  {id:3,name:"Café Aurora",category:"Cafeteria",city:"Campinas, SP",score:84,status:"Contatado",site:false,phone:"(19) 98813-2711",initials:"CA",tone:"amber"},
  {id:4,name:"Vitta Pilates",category:"Estúdio de pilates",city:"Campinas, SP",score:78,status:"Mensagem preparada",site:true,phone:"(19) 99701-4228",initials:"VP",tone:"blue"},
  {id:5,name:"Almeida & Reis Contábil",category:"Contabilidade",city:"Campinas, SP",score:74,status:"Novo",site:true,phone:"(19) 98125-9010",initials:"AR",tone:"rose"},
];
const navigation = [["dashboard","▦","Visão geral"],["campanhas","◉","Campanhas"],["leads","♙","Leads"],["crm","▥","CRM"],["mensagens","✉","Mensagens"],["configuracoes","⚙","Configurações"]];
const subtitles:Record<string,string> = {campanhas:"Crie, acompanhe e controle suas buscas.",leads:"Empresas qualificadas, sem duplicidades.",crm:"Acompanhe cada oportunidade até o fechamento.",mensagens:"Revise e aprove cada contato antes do envio.",configuracoes:"Preferências, segurança e integrações."};

function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function Company({lead}:{lead:Lead}){return <div className="company"><span className={`company-avatar ${lead.tone}`}>{lead.initials}</span><div><b>{lead.name}</b><small>{lead.category} · {lead.city}</small></div></div>}

export default function Workspace({page}:{page:string}){
  const [dark,setDark]=useState(false); const [notice,setNotice]=useState(""); const [active,setActive]=useState(true);
  const title=page==="dashboard"?"Bom dia, Marco!":page==="crm"?"Pipeline comercial":page==="campanhas"?"Campanhas":page==="leads"?"Leads encontrados":page==="mensagens"?"Fila de mensagens":"Configurações";
  return <div className={`app ${dark?"dark":""}`}>
    <aside className="sidebar"><Link href="/dashboard" className="brand"><span className="brand-mark">P</span>ProspectWise <b>AI</b></Link><nav>{navigation.map(([href,icon,label])=><Link key={href} href={`/${href}`} className={page===href?"active":""}><span>{icon}</span>{label}{href==="mensagens"&&<em>12</em>}</Link>)}</nav><div className="sidebar-bottom"><div className="plan"><span>Plano gratuito</span><b>42 de 100 leads</b><i><span/></i><button onClick={()=>setNotice("Planos pagos estarão disponíveis em breve.")}>Fazer upgrade</button></div><div className="profile"><span className="avatar">MS</span><div><b>Marco Silva</b><small>marco@prospectwise.ai</small></div></div></div></aside>
    <main><header><div className="search">⌕ <input aria-label="Busca global" placeholder="Buscar leads, campanhas..."/><kbd>⌘ K</kbd></div><div className="header-actions"><button className="icon-button" onClick={()=>setDark(!dark)} aria-label="Alternar tema">{dark?"☀":"☾"}</button><button className="icon-button" aria-label="Notificações">♢<span className="dot"/></button><Link className="primary compact" href="/campanhas/nova">＋ Nova campanha</Link></div></header>
    <section className="content"><div className="page-heading"><div><h1>{title}</h1><p>{page==="dashboard"?"Aqui está o resumo da sua prospecção hoje.":subtitles[page]}</p></div>{!["dashboard","configuracoes"].includes(page)&&<Link href="/campanhas/nova" className="primary">＋ Nova campanha</Link>}</div>{notice&&<div className="toast">✓ {notice}<button onClick={()=>setNotice("")}>×</button></div>}
      {page==="dashboard"&&<Dashboard active={active} setActive={setActive} setNotice={setNotice}/>} {page==="campanhas"&&<Campaigns active={active} setActive={setActive}/>} {page==="leads"&&<Leads/>} {page==="crm"&&<CRM/>} {page==="mensagens"&&<Messages setNotice={setNotice}/>} {page==="configuracoes"&&<Settings setNotice={setNotice}/>} </section></main>
  </div>
}

function Dashboard({active,setActive,setNotice}:{active:boolean;setActive:(v:boolean)=>void;setNotice:(v:string)=>void}){const metrics=[["Leads encontrados","248","+12,5%","♙","blue"],["Mensagens preparadas","64","+8,2%","✉","violet"],["Mensagens enviadas","39","+18,4%","➤","green"],["Taxa de resposta","23,1%","+4,3%","↩","amber"]];return <><div className="metrics">{metrics.map(([label,value,change,icon,tone])=><article className="metric" key={label}><div className={`metric-icon ${tone}`}>{icon}</div><span>{label}</span><h2>{value}</h2><p><b>↗ {change}</b> vs. últimos 30 dias</p></article>)}</div><div className="grid-two"><article className="panel performance"><div className="panel-head"><div><h3>Desempenho</h3><p>Resultados dos últimos 7 dias</p></div><select><option>Últimos 7 dias</option></select></div><div className="chart"><div className="chart-bars">{[32,48,41,72,61,88,80].map((n,i)=><i key={i} style={{height:`${n}%`}}><span style={{height:`${Math.max(12,n/3)}%`}}/></i>)}</div><div className="days"><span>Seg</span><span>Ter</span><span>Qua</span><span>Qui</span><span>Sex</span><span>Sáb</span><span>Dom</span></div></div><div className="legend"><span><i className="sent"/>Mensagens enviadas</span><span><i className="replies"/>Respostas</span></div></article><article className="panel campaign-card"><div className="panel-head"><div><Badge tone={active?"success":"warning"}>● {active?"Ativa":"Pausada"}</Badge><h3>Clínicas odontológicas</h3><p>Campinas, SP</p></div><button>•••</button></div><div className="progress-row"><span>Progresso</span><b>68%</b></div><div className="bar"><span/></div><div className="campaign-stats"><div><span>Leads</span><b>68 <small>/ 100</small></b></div><div><span>Enviadas</span><b>42</b></div><div><span>Respostas</span><b>11</b></div></div><div className="next-send"><span>◷</span><div><small>Próximo envio</small><b>{active?"Hoje, 14:30":"Campanha pausada"}</b></div></div><button className="secondary full" onClick={()=>{setActive(!active);setNotice(active?"Campanha pausada com segurança.":"Campanha reativada no modo simulado.")}}>{active?"Ⅱ Pausar campanha":"▶ Retomar campanha"}</button></article></div><article className="panel leads-panel"><div className="panel-head"><div><h3>Leads recentes</h3><p>Últimas empresas encontradas</p></div><Link href="/leads">Ver todos →</Link></div><LeadTable rows={leads.slice(0,4)}/></article></>}

function Campaigns({active,setActive}:{active:boolean;setActive:(v:boolean)=>void}){return <div className="cards-list"><article className="panel campaign-wide"><div><Badge tone={active?"success":"warning"}>● {active?"Ativa":"Pausada"}</Badge><h3>Clínicas odontológicas — Campinas</h3><p>Sites · Bots para WhatsApp · Landing pages</p></div><div className="campaign-numbers"><span><b>68</b> leads</span><span><b>42</b> enviadas</span><span><b>11</b> respostas</span><span><b>3</b> interessados</span></div><button className="secondary" onClick={()=>setActive(!active)}>{active?"Pausar":"Retomar"}</button></article><div className="empty"><span>＋</span><h3>Crie sua próxima campanha</h3><p>Pesquise empresas por cidade e segmento com limites seguros.</p><Link href="/campanhas/nova" className="primary">Criar campanha</Link></div></div>}
function Leads(){const [query,setQuery]=useState("");const filtered=useMemo(()=>leads.filter(l=>l.name.toLowerCase().includes(query.toLowerCase())),[query]);return <article className="panel leads-panel"><div className="filters"><div className="search wide">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa..."/></div><select><option>Todos os status</option></select><select><option>Maior score</option></select></div><LeadTable rows={filtered}/></article>}
function LeadTable({rows}:{rows:Lead[]}){return <div className="table-wrap"><table><thead><tr><th>Empresa</th><th>Score</th><th>Status</th><th>Presença digital</th><th>Contato</th><th/></tr></thead><tbody>{rows.map(l=><tr key={l.id}><td><Company lead={l}/></td><td><span className={`score ${l.score>85?"high":""}`}>{l.score}</span></td><td><Badge tone={l.status==="Interessado"?"success":l.status==="Respondeu"?"info":l.status==="Contatado"?"purple":"neutral"}>{l.status}</Badge></td><td><span className={l.site?"site-ok":"site-missing"}>● {l.site?"Site encontrado":"Sem site"}</span></td><td><b className="phone">{l.phone}</b></td><td><Link href={`/leads/${l.id}`} className="more">•••</Link></td></tr>)}</tbody></table>{!rows.length&&<div className="empty small"><h3>Nenhum lead encontrado</h3><p>Tente buscar outro nome.</p></div>}</div>}
function CRM(){const cols=[["Novo",leads.slice(4)],["Mensagem preparada",leads.slice(3,4)],["Contatado",leads.slice(2,3)],["Respondeu",leads.slice(1,2)],["Interessado",leads.slice(0,1)]] as [string,Lead[]][];return <div className="kanban">{cols.map(([name,items],i)=><section className="kanban-col" key={name}><header><span className={`kanban-dot k${i}`}/><b>{name}</b><em>{items.length}</em></header>{items.map(l=><article className="lead-card" key={l.id}><Company lead={l}/><div><span className="score">{l.score}</span><small>{l.city}</small></div></article>)}<button>＋ Adicionar lead</button></section>)}</div>}
function Messages({setNotice}:{setNotice:(v:string)=>void}){const [approved,setApproved]=useState(false);return <div className="grid-two messages-grid"><article className="panel message-list"><div className="panel-head"><div><h3>Aguardando aprovação</h3><p>12 mensagens preparadas</p></div><Badge tone="warning">Revisão manual</Badge></div>{leads.slice(0,3).map((l,i)=><button className={`message-item ${i===0?"selected":""}`} key={l.id}><span className={`company-avatar ${l.tone}`}>{l.initials}</span><span><b>{l.name}</b><small>Há {i?18:4} minutos</small></span><em>›</em></button>)}</article><article className="panel message-editor"><div className="panel-head"><div><h3>Sorriso Prime Odontologia</h3><p>{leads[0].phone} · Campinas</p></div><Badge tone="success">Score 92</Badge></div><label>Mensagem personalizada<textarea defaultValue={"Olá! Vi que a Sorriso Prime atende em Campinas e percebi uma oportunidade de fortalecer a presença digital da clínica. Trabalho com criação de sites e automações que facilitam o contato com novos pacientes. Posso compartilhar uma ideia rápida, sem compromisso?\n\nSe preferir não receber novas mensagens, é só me avisar por aqui."}/></label><div className="compliance">✓ Inclui opção de descadastro e não contém informações inventadas.</div><div className="editor-actions"><button className="secondary" onClick={()=>setNotice("Rascunho salvo.")}>Salvar rascunho</button><button className="primary" onClick={()=>{setApproved(true);setNotice("Mensagem adicionada à fila simulada.")}}>{approved?"✓ Aprovada":"Aprovar para a fila"}</button></div></article></div>}
function Settings({setNotice}:{setNotice:(v:string)=>void}){function save(e:FormEvent){e.preventDefault();setNotice("Configurações salvas.")}return <form className="settings-grid" onSubmit={save}><article className="panel"><h3>Limites de envio</h3><p>Controles aplicados antes de cada tentativa.</p><label>Limite diário<input type="number" defaultValue="25" min="1" max="50"/></label><label>Intervalo mínimo<select defaultValue="5"><option value="5">5 minutos</option><option value="10">10 minutos</option></select></label><div className="row"><label>Início<input type="time" defaultValue="09:00"/></label><label>Fim<input type="time" defaultValue="18:00"/></label></div></article><article className="panel"><h3>Integrações</h3><p>O MVP usa provedores seguros de demonstração.</p>{[["⌕","Busca de empresas","MockLeadProvider"],["◉","WhatsApp","MockWhatsAppProvider"],["✦","Geração com IA","Gerador local seguro"]].map(x=><div className="integration" key={x[1]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><Badge tone="info">Simulado</Badge></div>)}</article><button className="primary save">Salvar configurações</button></form>}
