export const CRM_STAGES = ["Novo","Mensagem preparada","Contatado","Respondeu","Interessado","Reunião","Proposta","Cliente","Sem interesse"] as const;
export type CrmStage=(typeof CRM_STAGES)[number];
export type MockLead={id:string;name:string;shortName:string;category:string;city:string;score:number;status:CrmStage;site:boolean;phone:string;initials:string;tone:string;analysis:string;services:string[]};
export const MOCK_LEADS:MockLead[]=[
 {id:"lead-sorriso-prime",name:"Sorriso Prime Odontologia",shortName:"Sorriso Prime",category:"Clínica odontológica",city:"Campinas, SP",score:92,status:"Interessado",site:false,phone:"(19) 99542-8170",initials:"SP",tone:"mint",analysis:"Não possui site identificado nos dados disponíveis. Uma presença digital profissional pode facilitar a descoberta local e novos contatos.",services:["Criação de site","Bot para WhatsApp","Landing page"]},
 {id:"lead-studio-helena",name:"Studio Helena Arquitetura",shortName:"Studio Helena",category:"Arquitetura",city:"Campinas, SP",score:87,status:"Respondeu",site:true,phone:"(19) 99182-0406",initials:"SH",tone:"violet",analysis:"Possui site, mas pode centralizar a captação de projetos e agilizar a triagem de novos clientes com automação.",services:["Landing page","Agente de IA","Automação de atendimento"]},
 {id:"lead-cafe-aurora",name:"Café Aurora",shortName:"Café Aurora",category:"Cafeteria",city:"Campinas, SP",score:84,status:"Contatado",site:false,phone:"(19) 98813-2711",initials:"CA",tone:"amber",analysis:"Não possui site identificado. Uma página local com cardápio, localização e contato pode melhorar a presença digital.",services:["Criação de site","Landing page","Bot para WhatsApp"]},
 {id:"lead-vitta-pilates",name:"Vitta Pilates",shortName:"Vitta Pilates",category:"Estúdio de pilates",city:"Campinas, SP",score:78,status:"Mensagem preparada",site:true,phone:"(19) 99701-4228",initials:"VP",tone:"blue",analysis:"Possui site e pode melhorar a conversão de interessados com agendamento e respostas automatizadas.",services:["Automação de agendamento","Bot para WhatsApp"]},
 {id:"lead-almeida-reis",name:"Almeida & Reis Contábil",shortName:"Almeida & Reis",category:"Contabilidade",city:"Campinas, SP",score:74,status:"Novo",site:true,phone:"(19) 98125-9010",initials:"AR",tone:"rose",analysis:"Possui site e pode reduzir tarefas repetitivas de atendimento e qualificação de novos clientes.",services:["Agente de IA","Automação de atendimento"]},
];
export function findLeadById(id:string|undefined|null){return id?MOCK_LEADS.find(lead=>lead.id===id):undefined}
export function buildLeadMessage(lead:MockLead){const siteContext=lead.site?"Vi que vocês já possuem presença digital":"Não encontrei um site nos dados disponíveis";return `Olá! ${siteContext} para a ${lead.name}, de ${lead.category.toLowerCase()} em ${lead.city}. Percebi uma oportunidade relacionada a ${lead.services.slice(0,2).join(" e ").toLowerCase()}. Posso compartilhar uma ideia rápida, sem compromisso?\n\nSe preferir não receber novas mensagens, é só me avisar por aqui.`}
