export type SearchCompaniesInput={city:string;state?:string;category:string;limit:number};
export type LeadResult={externalId:string;name:string;phone?:string;website?:string;address:string;category:string;rating?:number;reviews?:number;mapsUrl?:string};
export interface LeadProvider{readonly name:"mock"|"outscraper";search(input:SearchCompaniesInput):Promise<LeadResult[]>}

const MOCK_NAMES=["Sorriso Prime","Studio Helena","Café Aurora","Vitta Pilates","Almeida & Reis","Espaço Manacá","Clínica Horizonte","Bistrô Central","Ateliê Norte","Orbe Consultoria"];
export class MockLeadProvider implements LeadProvider{readonly name="mock" as const;async search(input:SearchCompaniesInput){return Array.from({length:input.limit},(_,i)=>({externalId:`mock-${slug(input.city)}-${slug(input.category)}-${i+1}`,name:MOCK_NAMES[i%MOCK_NAMES.length]+(i>=MOCK_NAMES.length?` ${i+1}`:""),phone:`+55199${String(90000000+i).padStart(8,"0")}`,website:i%3===0?undefined:`https://empresa-${i+1}.example`,address:`${input.city}${input.state?`, ${input.state}`:""}`,category:input.category,rating:4+(i%10)/10,reviews:18+i*7,mapsUrl:`https://maps.google.com/?q=${encodeURIComponent(MOCK_NAMES[i%MOCK_NAMES.length])}`}))}}

type OutscraperPlace={place_id?:string;google_id?:string;name?:string;phone?:string;site?:string;full_address?:string;category?:string;type?:string;rating?:number;reviews?:number;google_maps_url?:string};
export class OutscraperLeadProvider implements LeadProvider{readonly name="outscraper" as const;constructor(private readonly apiKey:string,private readonly fetcher:typeof fetch=fetch){if(!apiKey.trim())throw new Error("OUTSCRAPER_API_KEY não configurada.")}async search(input:SearchCompaniesInput){const response=await this.fetcher("https://api.outscraper.com/google-maps-search",{method:"POST",headers:{"Content-Type":"application/json","X-API-KEY":this.apiKey},body:JSON.stringify({query:[`${input.category}, ${input.city}${input.state?`, ${input.state}`:""}, Brasil`],limit:input.limit,async:false})});if(!response.ok)throw new Error(`Outscraper respondeu com status ${response.status}.`);const payload=await response.json() as {data?:OutscraperPlace[]|OutscraperPlace[][];status?:string};if(payload.status==="Pending")throw new Error("A busca da Outscraper está em processamento. Tente novamente em instantes.");const raw=Array.isArray(payload.data?.[0])?(payload.data as OutscraperPlace[][]).flat():((payload.data??[]) as OutscraperPlace[]);return raw.map((place,index)=>({externalId:place.place_id??place.google_id??`outscraper-${index}`,name:place.name?.trim()??"",phone:place.phone,website:place.site,address:place.full_address??`${input.city}${input.state?`, ${input.state}`:""}`,category:place.category??place.type??input.category,rating:place.rating,reviews:place.reviews,mapsUrl:place.google_maps_url}))}}

export function createLeadProvider(name:"mock"|"outscraper",env:{OUTSCRAPER_API_KEY?:string},fetcher?:typeof fetch):LeadProvider{return name==="outscraper"?new OutscraperLeadProvider(env.OUTSCRAPER_API_KEY??"",fetcher):new MockLeadProvider()}
function slug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}

export type MessageRequest={to:string;body:string;idempotencyKey:string};
export interface WhatsAppProvider{send(input:MessageRequest):Promise<{providerMessageId:string}>}
export class MockWhatsAppProvider implements WhatsAppProvider{async send(input:MessageRequest){return {providerMessageId:`mock-${input.idempotencyKey}`}}}
export class MetaWhatsAppProvider implements WhatsAppProvider{async send():Promise<{providerMessageId:string}>{throw new Error("Envios reais exigem aprovação manual e credenciais da Meta.")}}
