import type {CrmStage} from "./crm";
export type WorkspaceLead={id:string;campaignId:string;name:string;shortName:string;category:string;city:string;state?:string;score:number;status:CrmStage;site:boolean;website?:string|null;phone:string;rating?:number|null;reviews?:number|null;provider?:string;notes?:string|null;createdAt?:string;initials:string;tone:string;analysis:string;services:string[]};
export type WorkspaceCampaign={id:string;name:string;city:string;status:string;services:string[];createdAt?:string;lastActivityAt?:string;metrics:{companies:number;messages:number;responses:number;clients:number;progress:number;interested?:number;averageScore?:number}};
export type WorkspaceActivity={id:string;type:string;note:string;createdAt:string;leadId?:string;campaignId:string};
export type WorkspaceMessage={campaignId:string;leadId?:string;status:string;createdAt?:string};
export type WorkspaceData={leads:WorkspaceLead[];campaigns:WorkspaceCampaign[];activities:WorkspaceActivity[];messages:WorkspaceMessage[]};
export type TimelineEvent={id:string;title:string;description:string;createdAt:string;leadId?:string};
export type CampaignDetailData={campaign:WorkspaceCampaign&{segment:string;goal:number};leads:WorkspaceLead[];messages:{leadId:string;status:string}[];events:TimelineEvent[];metrics:WorkspaceCampaign["metrics"]};
export function buildWorkspaceLeadMessage(lead:WorkspaceLead){const siteContext=lead.site?"Vi que vocês já possuem presença digital":"Não encontrei um site nos dados disponíveis";return `Olá! ${siteContext} para a ${lead.name}, de ${lead.category.toLowerCase()} em ${lead.city}. Percebi uma oportunidade relacionada a ${(lead.services.length?lead.services:["presença digital"]).slice(0,2).join(" e ").toLowerCase()}. Posso compartilhar uma ideia rápida, sem compromisso?\n\nSe preferir não receber novas mensagens, é só me avisar por aqui.`}
