import {createClient} from "@supabase/supabase-js";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,email=process.env.DEMO_USER_EMAIL;
if(process.env.NODE_ENV==="production")throw new Error("O seed de demonstração não pode rodar em produção.");
if(!url||!key||!email)throw new Error("Configure NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY e DEMO_USER_EMAIL.");
const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
const {data:list,error:listError}=await supabase.auth.admin.listUsers();if(listError)throw listError;let user=list.users.find(item=>item.email===email);if(!user){const {data,error}=await supabase.auth.admin.createUser({email,email_confirm:true,password:crypto.randomUUID()+"Aa1!"});if(error)throw error;user=data.user}
const campaignId="10000000-0000-4000-8000-000000000001",leadId="20000000-0000-4000-8000-000000000001",messageId="30000000-0000-4000-8000-000000000001";
const {error}=await supabase.from("campaigns").upsert({id:campaignId,user_id:user.id,name:"Clínicas odontológicas",city:"Campinas",state:"SP",segment:"Odontologia",company_limit:100,services:["Criação de site","Bot para WhatsApp"],daily_limit:25,status:"draft"},{onConflict:"id"});if(error)throw error;
const {error:leadError}=await supabase.from("leads").upsert({id:leadId,user_id:user.id,campaign_id:campaignId,external_id:"demo-sorriso-prime",name:"Sorriso Prime Odontologia",phone:"(19) 99542-8170",address:"Campinas, SP",city:"Campinas",state:"SP",category:"Clínica odontológica",rating:4.8,reviews:46,crm_stage:"Novo"},{onConflict:"id"});if(leadError)throw leadError;
const now=new Date().toISOString();const {error:analysisError}=await supabase.from("lead_analyses").upsert({id:"40000000-0000-4000-8000-000000000001",user_id:user.id,lead_id:leadId,campaign_id:campaignId,score:70,classification:"Bom",priority:"Média",opportunities:["Criar presença digital própria"],recommended_services:[{name:"Site institucional",reason:"Sem website",priority:"Alta",rule:"no_website"}],reasons:["Sem website: +30"],missing_data:[],rules_version:"lead-intelligence-v1.0.0",analyzed_at:now,updated_at:now},{onConflict:"lead_id"});if(analysisError)throw analysisError;
const {error:messageError}=await supabase.from("messages").upsert({id:messageId,user_id:user.id,lead_id:leadId,campaign_id:campaignId,body:"Mensagem de demonstração — nenhum envio real será realizado.",status:"Rascunho"},{onConflict:"id"});if(messageError)throw messageError;
console.log(`Seed concluído para ${email}. IDs estáveis impediram duplicação.`);
