import {CSV_FIELDS,type CsvColumnMapping,type CsvField,type CsvPreviewRow,type NormalizedCsvLead} from "./types";
export const MAX_CSV_BYTES=2*1024*1024;
const aliases:Record<CsvField,string[]>={name:["nome","empresa","company","company_name","business","business_name","name"],phone:["telefone","fone","celular","whatsapp","phone","mobile","telephone"],website:["site","website","web_site","url","domain","dominio"],address:["endereco","endereço","endereco_completo","logradouro","address","street","full_address"],city:["cidade","municipio","município","city","town"],state:["estado","uf","state","province"],category:["categoria","segmento","ramo","category","type","business_type"],rating:["nota","avaliacao","avaliação","rating","stars","score"],reviews:["avaliacoes","avaliações","numero_avaliacoes","quantidade_avaliacoes","reviews","review_count","reviews_count"],mapsUrl:["google_maps_url","googlemapsurl","maps_url","map_url","google_maps","googlemaps"],instagram:["instagram","instagram_url","insta"],facebook:["facebook","facebook_url","fb"]};
function normalizedHeader(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")}
const aliasLookup=new Map<string,CsvField>();for(const field of CSV_FIELDS)for(const alias of aliases[field])aliasLookup.set(normalizedHeader(alias),field);
export function suggestField(header:string):CsvField|"ignore"{return aliasLookup.get(normalizedHeader(header))??"ignore"}
function countDelimiter(line:string,delimiter:string){let count=0,quoted=false;for(let i=0;i<line.length;i++){if(line[i]==='"')quoted=!quoted;else if(!quoted&&line[i]===delimiter)count++}return count}
export function detectDelimiter(text:string){const line=text.replace(/^\uFEFF/,"").split(/\r?\n/,1)[0]??"";return [",",";","\t"].sort((a,b)=>countDelimiter(line,b)-countDelimiter(line,a))[0]}
export function parseCsv(text:string,delimiter=detectDelimiter(text)){if(new TextEncoder().encode(text).length>MAX_CSV_BYTES)throw new Error("Arquivo maior que 2 MB.");const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;const source=text.replace(/^\uFEFF/,"");for(let i=0;i<source.length;i++){const char=source[i];if(char==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(cell);cell=""}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&source[i+1]==='\n')i++;row.push(cell);cell="";if(row.some(value=>value.trim()))rows.push(row);row=[]}else cell+=char}row.push(cell);if(row.some(value=>value.trim()))rows.push(row);if(quoted)throw new Error("CSV contém aspas não finalizadas.");if(rows.length>5001)throw new Error("CSV excede o limite de 5.000 linhas.");return rows}
function plain(value:string){return value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,"").trim()}
export function neutralizeFormula(value:string){const clean=plain(value);return /^[=@]/.test(clean)||/^[+-](?!\d[\d\s().-]*$)/.test(clean)?`'${clean}`:clean}
export function normalizePhone(value:string){const raw=plain(value);if(!raw)return null;const digits=raw.replace(/\D/g,"");if(digits.length<8||digits.length>15)return null;return digits.startsWith("55")?`+${digits}`:`+55${digits}`}
export function normalizeUrl(value:string){const raw=plain(value);if(!raw)return null;try{const candidate=/^https?:\/\//i.test(raw)?raw:`https://${raw}`;const url=new URL(candidate);if(!url.hostname.includes("."))return null;url.hash="";return url.toString().replace(/\/$/,"")}catch{return null}}
export function normalizeName(value:string){return neutralizeFormula(value).replace(/\s+/g," ")}
export function normalizeCity(value:string){return neutralizeFormula(value).replace(/\s+/g," ").replace(/(^|\s)\p{L}/gu,letter=>letter.toLocaleUpperCase("pt-BR"))}
export function normalizeState(value:string){return plain(value).replace(/[^a-z]/gi,"").slice(0,2).toUpperCase()}
function decimal(value:string){const clean=plain(value).replace(",",".").replace(/[^0-9.-]/g,"");const number=Number(clean);return Number.isFinite(number)?number:null}
function integer(value:string){const number=decimal(value);return number===null?null:Math.max(0,Math.round(number))}
export function mappingFor(headers:string[],manual:CsvColumnMapping={}):CsvColumnMapping{return Object.fromEntries(headers.map(header=>[header,manual[header]??suggestField(header)]))}
export function normalizeRow(headers:string[],cells:string[],mapping:CsvColumnMapping,line:number):CsvPreviewRow{const raw:Partial<Record<CsvField,string>>={};headers.forEach((header,index)=>{const field=mapping[header];if(field&&field!=="ignore"&&!raw[field])raw[field]=cells[index]??""});const lead:NormalizedCsvLead={name:normalizeName(raw.name??""),phone:normalizePhone(raw.phone??""),website:normalizeUrl(raw.website??""),address:neutralizeFormula(raw.address??"")||null,city:normalizeCity(raw.city??"")||null,state:normalizeState(raw.state??"")||null,category:neutralizeFormula(raw.category??"")||null,rating:decimal(raw.rating??""),reviews:integer(raw.reviews??""),mapsUrl:normalizeUrl(raw.mapsUrl??""),instagram:normalizeUrl(raw.instagram??""),facebook:normalizeUrl(raw.facebook??""),provider:"csv_import"};const errors:string[]=[];if(!lead.name)errors.push("Nome ausente");if(raw.phone&& !lead.phone)errors.push("Telefone inválido");if(raw.website&&!lead.website)errors.push("Site inválido");if(raw.rating&&lead.rating===null)errors.push("Nota inválida");const missingFields=CSV_FIELDS.filter(field=>field!=="name"&&(lead[field]===null||lead[field]===""));return {line,valid:errors.length===0,duplicate:false,missingFields,errors,lead}}
export function duplicateKeys(lead:NormalizedCsvLead){const keys:string[]=[];if(lead.phone)keys.push(`phone:${lead.phone}`);if(lead.website)keys.push(`domain:${new URL(lead.website).hostname.replace(/^www\./,"").toLowerCase()}`);if(lead.name&&lead.city)keys.push(`namecity:${normalizeName(lead.name).toLowerCase()}|${normalizeCity(lead.city).toLowerCase()}`);if(lead.address)keys.push(`address:${lead.address.toLowerCase().replace(/\W/g,"")}`);if(lead.mapsUrl)keys.push(`maps:${lead.mapsUrl.toLowerCase()}`);return keys}
