create extension if not exists pgcrypto;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.campaigns (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, city text not null, state text not null, segment text not null, company_limit integer not null default 25 check(company_limit>0), services jsonb not null default '[]', daily_limit integer not null default 25, send_start time not null default '09:00', send_end time not null default '18:00', status text not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id));
create table if not exists public.leads (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, campaign_id uuid not null, external_id text, name text not null, phone text, website text, address text, city text, state text, category text, rating numeric(2,1), reviews integer, maps_url text, crm_stage text not null default 'Novo', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id), foreign key(campaign_id,user_id) references public.campaigns(id,user_id) on delete cascade);
create unique index if not exists leads_user_external_unique on public.leads(user_id,external_id) where external_id is not null;
create table if not exists public.lead_analyses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, lead_id uuid not null, campaign_id uuid not null, score integer not null check(score between 0 and 100), classification text not null, priority text not null, opportunities jsonb not null default '[]', recommended_services jsonb not null default '[]', reasons jsonb not null default '[]', missing_data jsonb not null default '[]', rules_version text not null, analyzed_at timestamptz not null default now(), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(lead_id), foreign key(lead_id,user_id) references public.leads(id,user_id) on delete cascade, foreign key(campaign_id,user_id) references public.campaigns(id,user_id) on delete cascade);
create table if not exists public.messages (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, lead_id uuid not null, campaign_id uuid not null, body text not null, status text not null default 'Rascunho', attempts integer not null default 0, scheduled_at timestamptz, approved_at timestamptz, sent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id), foreign key(lead_id,user_id) references public.leads(id,user_id) on delete cascade, foreign key(campaign_id,user_id) references public.campaigns(id,user_id) on delete cascade);
create table if not exists public.message_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, message_id uuid not null, provider_id text, status text not null, error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(message_id,user_id) references public.messages(id,user_id) on delete cascade);
create table if not exists public.conversations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, campaign_id uuid not null, lead_id uuid not null, status text not null, manual_takeover boolean not null default false, last_message_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(campaign_id,user_id) references public.campaigns(id,user_id) on delete cascade, foreign key(lead_id,user_id) references public.leads(id,user_id) on delete cascade);
create table if not exists public.crm_activities (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, campaign_id uuid not null, lead_id uuid not null, type text not null, note text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(campaign_id,user_id) references public.campaigns(id,user_id) on delete cascade, foreign key(lead_id,user_id) references public.leads(id,user_id) on delete cascade);
create table if not exists public.opt_outs (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, phone text not null, reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,phone));
create table if not exists public.provider_settings (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, active_provider text not null default 'mock', encrypted_config jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.app_settings (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade, daily_limit integer not null default 25, interval_minutes integer not null default 5, send_start time not null default '09:00', send_end time not null default '18:00', manual_approval boolean not null default true, search_limit integer not null default 10, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,name) values(new.id,coalesce(new.email,''),new.raw_user_meta_data->>'name') on conflict(id) do nothing; return new; end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

do $$ declare t text; begin foreach t in array array['campaigns','leads','lead_analyses','messages','message_attempts','conversations','crm_activities','opt_outs','provider_settings','app_settings'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists own_rows on public.%I',t); execute format('create policy own_rows on public.%I for all using (user_id = auth.uid()) with check (user_id = auth.uid())',t); end loop; end $$;
alter table public.profiles enable row level security;
drop policy if exists own_profile on public.profiles;
create policy own_profile on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());

create index if not exists campaigns_user_status_idx on public.campaigns(user_id,status);
create index if not exists leads_user_campaign_stage_idx on public.leads(user_id,campaign_id,crm_stage);
create index if not exists lead_analyses_user_score_idx on public.lead_analyses(user_id,score desc);
create index if not exists messages_user_campaign_idx on public.messages(user_id,campaign_id,status);
create index if not exists crm_activities_user_lead_idx on public.crm_activities(user_id,lead_id,created_at desc);
